//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorProjectV1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int TokenID { get; set; }
        public int DeviceID { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
